### ISSUE TITLE
Actions not parsed correctly

### ISSUE THREAD

**Issue by pierg** [pierg/cloud-guardian#5]
To reproduce run main.py from main branch:

Logs:

"Supported actions for node Eve having permissions * "

However from data/aws_example_wildcards we have that 

users.json

"UserName": "Eve",
      "UserArn": "arn:aws:iam::123456789012:user/Eve",
      "CreateDate": "2023-01-01T12:00:00Z",
      "AttachedPolicies": [
        {
          "PolicyName": "BasicUserAccess",
          "PolicyArn": "arn:aws:iam::123456789012:policy/BasicUserAccess"
        }
      ]
      
      
   identities_policies.json
   
   "PolicyName": "BasicUserAccess",
      "PolicyArn": "arn:aws:iam::123456789012:policy/BasicUserAccess",
      "PolicyDocument": {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:GetObject",
              "s3:List*",
              "s3:Put*"
            ],
            "Resource": "*"
          }
        ]
      }
      
      so Eve should have 
      
       "s3:GetObject",
              "s3:List*",
              "s3:Put*"
              
              
              as permissions (i.e. "SpecifiedActions")

**Comment by glethuillier** [comment]
Fixed my allowing multiple edges between a given pair of nodes using `nx.MultiDiGraph` (https://github.com/pierg/cloud-guardian/commit/d558cc4d8abb0de1aebde35340e61b380f3b0ff7)
